### ISSUE TITLE
Cannot decompress data compressed by this tool.

### ISSUE THREAD

**Issue by MarekKnapek** [zhenrong-wang/bcomp#7]
Steps to reproduce:

```
$ ./bcomp -c data_a.dat data_b.dat
INFO: Compressed file data_a.dat to data_b.dat.bc . Return Value: 0.
Repository: https://github.com/zhenrong-wang/bcomp
```
```
$ ./bcomp -d data_b.dat.bc data_c.dat
INFO: Decompressed file data_b.dat.bc to data_c.dat .
Repository: https://github.com/zhenrong-wang/bcomp
```
[data_a.zip](https://github.com/zhenrong-wang/bcomp/files/15328980/data_a.zip)

**Comment by MarekKnapek** [comment]
The original file is 650 bytes long, compressed file is 126 bytes long, decompressed file is 394 bytes long. This is not lossless compression.

**Comment by MarekKnapek** [comment]
Discovered by fuzzing.

**Comment by zhenrong-wang** [comment]
![mmexport1715826952057.png](https://github.com/zhenrong-wang/bcomp/assets/59274212/6bb79d27-de8a-4c8b-8294-17d7c5cb81c1)

With the latest branch main code and the data file you provided in this issue, I didn't reproduce the problem.

Please take a look.

**Comment by MarekKnapek** [comment]
![bcomp_7](https://github.com/zhenrong-wang/bcomp/assets/13893067/1177d336-2022-4b68-9b9a-0f41eb8260cc)

**Comment by MarekKnapek** [comment]
![bcomp_7b](https://github.com/zhenrong-wang/bcomp/assets/13893067/31e5d0f0-fb6c-42be-b044-e4eb4f690b4e)

**Comment by zhenrong-wang** [comment]
Let me try with MinGW. I have been testing on Ubuntu.

**Comment by zhenrong-wang** [comment]
This seems to be a cross-platform bug. Checking the root cause now. 

On Linux with the native gcc, the outcome is good. But on Windows I tested clang and gcc with MinGW, the outcome is not good. Let me figure out the reason.

**Comment by MarekKnapek** [comment]
No, it fails on Ubuntu Linux for me too. I'm using clang with ASAN.

![bcomp_7c](https://github.com/zhenrong-wang/bcomp/assets/13893067/533a13db-e2e1-4893-971c-1b5666324f16)


```
#217354 REDUCE cov: 126 ft: 497 corp: 201/41Kb lim: 1180 exec/s: 1509 rss: 407Mb L: 243/1031 MS: 3 ChangeBinInt-CopyPart-EraseBytes-
#217526 NEW    cov: 127 ft: 498 corp: 202/42Kb lim: 1180 exec/s: 1510 rss: 407Mb L: 994/1031 MS: 2 CopyPart-CopyPart-
#218107 REDUCE cov: 127 ft: 498 corp: 202/42Kb lim: 1180 exec/s: 1504 rss: 407Mb L: 795/1031 MS: 1 EraseBytes-
#219043 REDUCE cov: 127 ft: 498 corp: 202/42Kb lim: 1180 exec/s: 1510 rss: 407Mb L: 38/1031 MS: 1 EraseBytes-
#219240 REDUCE cov: 127 ft: 498 corp: 202/42Kb lim: 1180 exec/s: 1512 rss: 407Mb L: 524/1031 MS: 2 ChangeBinInt-EraseBytes-
#219926 REDUCE cov: 127 ft: 498 corp: 202/42Kb lim: 1180 exec/s: 1506 rss: 407Mb L: 368/1031 MS: 1 EraseBytes-
#220450 REDUCE cov: 127 ft: 498 corp: 202/42Kb lim: 1180 exec/s: 1509 rss: 407Mb L: 521/1031 MS: 4 ChangeBinInt-PersAutoDict-InsertRepeatedBytes-EraseBytes- DE: "\001;"-
#220453 REDUCE cov: 127 ft: 498 corp: 202/42Kb lim: 1180 exec/s: 1509 rss: 407Mb L: 770/1031 MS: 3 EraseBytes-CrossOver-InsertByte-
#221638 REDUCE cov: 127 ft: 498 corp: 202/42Kb lim: 1190 exec/s: 1497 rss: 407Mb L: 5/1031 MS: 5 PersAutoDict-ChangeBinInt-PersAutoDict-EraseBytes-InsertByte- DE: "\001\000\000\000"-"\377\373"-
#224365 REDUCE cov: 127 ft: 498 corp: 202/42Kb lim: 1210 exec/s: 1495 rss: 407Mb L: 457/1031 MS: 2 EraseBytes-InsertRepeatedBytes-
========== ========== ========== ==========
begin of bug report
original file len:                            523
file len after compression and decompression: 267
original file content:
63 23 63 23 01 f0 06 a7 a7 a7 a7 ff ff 23 01 f0 06 a7 a7 a7 a7 ff ff ff ff 1a fb fa 00 2e fb e6 5b fb 01 00 00 00 fa 00 ff fb 0f 1a c3 a7 a7 a7 a7 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 ce 50 50 50 50 70 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 4f 50 50 50 50 50 50 50 50 50 50 50 50 a7 a7 1a ff ff 1a fb fa 00 2e fb 3a fc cc 5f 00 00 e6 5b fb fa 00 ff fb 0f 1a c3 a7 a7 a7 a7 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 70 50 50 50 50 7b 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 d0 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 3a ac fa 00 00 00 fb 20 20
file content after compression and decompression:
63 23 63 23 01 f0 06 a7 a7 a7 a7 ff ff 23 01 f0 06 a7 a7 a7 a7 ff ff ff ff 1a fb fa 00 2e fb e6 5b fb 01 00 00 00 fa 00 ff fb 0f 1a c3 a7 a7 a7 a7 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 ce 50 50 50 50 70 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 4f 50 50 50 50 50 50 50 50 50 50 50 50 a7 a7 1a ff ff 1a fb fa 00 2e fb 3a fc cc 5f 00 00 e6 5b fb fa 00 ff fb 0f 1a c3 a7 a7 a7 a7 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 70 50 50 50 50 7b 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 d0 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3 b3
end of bug report
========== ========== ========== ==========
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2673==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x5c84ba4ca319 bp 0x7ffe714d7490 sp 0x7ffe714d72e0 T0)
==2673==The signal is caused by a WRITE memory access.
==2673==Hint: address points to the zero page.
    #0 0x5c84ba4ca319 in fuzz_1 /home/mk/repos/bcomp/bcomp.c:711:3
    #1 0x5c84ba4ca6b4 in LLVMFuzzerTestOneInput /home/mk/repos/bcomp/bcomp.c:729:2
    #2 0x5c84ba3d0cd4 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/mk/repos/bcomp/bcomp.elf+0x4dcd4) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #3 0x5c84ba3d03c9 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/mk/repos/bcomp/bcomp.elf+0x4d3c9) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #4 0x5c84ba3d1bb5 in fuzzer::Fuzzer::MutateAndTestOne() (/home/mk/repos/bcomp/bcomp.elf+0x4ebb5) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #5 0x5c84ba3d2715 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) (/home/mk/repos/bcomp/bcomp.elf+0x4f715) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #6 0x5c84ba3bf9ef in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/mk/repos/bcomp/bcomp.elf+0x3c9ef) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #7 0x5c84ba3ea076 in main (/home/mk/repos/bcomp/bcomp.elf+0x67076) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #8 0x717c6662a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 232274c0019767b821da1c6ebc2df43e60503035)
    #9 0x717c6662a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 232274c0019767b821da1c6ebc2df43e60503035)
    #10 0x5c84ba3b49d4 in _start (/home/mk/repos/bcomp/bcomp.elf+0x319d4) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mk/repos/bcomp/bcomp.c:711:3 in fuzz_1
==2673==ABORTING
MS: 1 EraseBytes-; base unit: d7d33d87b37ed9cba8d6e4b294fc2268fc269c02
artifact_prefix='./'; Test unit written to ./crash-4ce095feee7eed63deed5cb1fc7dd875d847c9ab
mk@wkpc:~/repos/bcomp/.github/workflows$
mk@wkpc:~/repos/bcomp/.github/workflows$
```

**Comment by zhenrong-wang** [comment]
Figuring out the root cause now. Would you please provide the compiler version so that I can test directly.

**Comment by MarekKnapek** [comment]
Another bug report:

![bcomp_7d](https://github.com/zhenrong-wang/bcomp/assets/13893067/1c91cfab-0251-49f0-a191-d6a27d1d85dc)

```
#205552 REDUCE cov: 126 ft: 499 corp: 195/39Kb lim: 1130 exec/s: 1557 rss: 407Mb L: 19/1042 MS: 1 EraseBytes-
#207658 REDUCE cov: 126 ft: 499 corp: 195/39Kb lim: 1150 exec/s: 1561 rss: 407Mb L: 328/1042 MS: 1 EraseBytes-
#209549 REDUCE cov: 127 ft: 500 corp: 196/40Kb lim: 1160 exec/s: 1552 rss: 407Mb L: 580/1042 MS: 1 InsertRepeatedBytes-
#210045 REDUCE cov: 127 ft: 500 corp: 196/40Kb lim: 1160 exec/s: 1555 rss: 407Mb L: 772/1042 MS: 1 EraseBytes-
#210380 REDUCE cov: 127 ft: 500 corp: 196/40Kb lim: 1160 exec/s: 1546 rss: 407Mb L: 49/1042 MS: 5 InsertByte-InsertByte-ChangeBinInt-ChangeBit-EraseBytes-
#210567 REDUCE cov: 127 ft: 501 corp: 197/40Kb lim: 1160 exec/s: 1548 rss: 407Mb L: 551/1042 MS: 2 ChangeByte-CopyPart-
#211749 REDUCE cov: 127 ft: 501 corp: 197/40Kb lim: 1170 exec/s: 1545 rss: 407Mb L: 535/1042 MS: 2 InsertByte-EraseBytes-
#215217 REDUCE cov: 127 ft: 501 corp: 197/40Kb lim: 1200 exec/s: 1548 rss: 407Mb L: 47/1042 MS: 3 CopyPart-EraseBytes-ChangeByte-
========== ========== ========== ==========
begin of bug report
original file len:                            580
file len after compression and decompression: 324
original file content:
c7 c7 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 33 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff f5 00 ff ff ff ff ff ff ff ff ff ff ff ff ff 01 00 01 00 ff ff ff ff ff ff ff ff ff 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 34 34 34 34 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 9b 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff ff ff ff ff f7 ff ff ff ff ff ff ff ff ff ff 34 34 34 34 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 00 00 00 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 05 00 00 00 ff ff ff 01 00 00 06 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 32 32 32 32 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 01
file content after compression and decompression:
c7 c7 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 33 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff f5 00 ff ff ff ff ff ff ff ff ff ff ff ff ff 01 00 01 00 ff ff ff ff ff ff ff ff ff 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 94 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 34 34 34 34 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 9b 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff ff ff ff ff f7 ff ff ff ff ff ff ff ff ff ff 34 34 34 34 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 00 00 00 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
end of bug report
========== ========== ========== ==========
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2793==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x5b44f2ff8319 bp 0x7ffeae6c6350 sp 0x7ffeae6c61a0 T0)
==2793==The signal is caused by a WRITE memory access.
==2793==Hint: address points to the zero page.
    #0 0x5b44f2ff8319 in fuzz_1 /home/mk/repos/bcomp/bcomp.c:711:3
    #1 0x5b44f2ff86b4 in LLVMFuzzerTestOneInput /home/mk/repos/bcomp/bcomp.c:729:2
    #2 0x5b44f2efecd4 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/mk/repos/bcomp/bcomp.elf+0x4dcd4) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #3 0x5b44f2efe3c9 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/mk/repos/bcomp/bcomp.elf+0x4d3c9) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #4 0x5b44f2effbb5 in fuzzer::Fuzzer::MutateAndTestOne() (/home/mk/repos/bcomp/bcomp.elf+0x4ebb5) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #5 0x5b44f2f00715 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) (/home/mk/repos/bcomp/bcomp.elf+0x4f715) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #6 0x5b44f2eed9ef in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/mk/repos/bcomp/bcomp.elf+0x3c9ef) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #7 0x5b44f2f18076 in main (/home/mk/repos/bcomp/bcomp.elf+0x67076) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)
    #8 0x7648a0c2a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 232274c0019767b821da1c6ebc2df43e60503035)
    #9 0x7648a0c2a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 232274c0019767b821da1c6ebc2df43e60503035)
    #10 0x5b44f2ee29d4 in _start (/home/mk/repos/bcomp/bcomp.elf+0x319d4) (BuildId: f8b26ad6e95714fbe564e7f49f9acb1f0f5b955e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mk/repos/bcomp/bcomp.c:711:3 in fuzz_1
==2793==ABORTING
MS: 3 PersAutoDict-ChangeBit-PersAutoDict- DE: "\365\000"-"\001\000\001\000"-; base unit: 420017afc5b47e733be71b6f422a7ecfc01c2550
artifact_prefix='./'; Test unit written to ./crash-b7f865bdd99272e8935b796e0e49b28872ff2852
mk@wkpc:~/repos/bcomp/.github/workflows$
```

My system is as follows:

```
Linux wkpc 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

My compiler is:

```
$ clang -v
Ubuntu clang version 18.1.3 (1)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/13
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/14
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/14
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

Start using fuzzing finally! I'm losing patience with you! I prepared everything for you ready to use!

Steps to start using fuzzing:
 - Add my repo as new git remote.
 - Sync my fuzzing branch.
 - Run the fucking script.
 - Enjoy the bug reports.

`git clone https://github.com/zhenrong-wang/bcomp.git`
`cd bcomp`
`git remote add mk https://github.com/MarekKnapek/bcomp.git`
`git fetch --all --force --prune`
`git checkout fuzz_v3`
`bash .github/workflows/job1.sh`

Now wait, bug report will be generated.

**Comment by zhenrong-wang** [comment]
Debugging now.

**Comment by zhenrong-wang** [comment]
This is still a FILE_END judgement issue. All the failed cases failed to write the last block to the decompression target file because the decompressor fails to detect the correct flag of the last state for this file. Trying to fix it now.

**Comment by zhenrong-wang** [comment]
> This is still a FILE_END judgement issue. All the failed cases failed to write the last block to the decompression target file because the decompressor fails to detect the correct flag of the last state for this file. Trying to fix it now.

It turns out the last state should be judged at the BIT level, but currently it is judged at BYTE level. Not precise enough for the decompressor. Should fix it quickly.
